### ISSUE TITLE
[1.12.2] Render Crash...Conflict with Light Level Overlay?

### ISSUE THREAD

**Issue by MokahTGS** [McJty/TheOneProbe#205]
Getting a crash with 4.18 on 1.12.2.  Forge Version 2503

I have light level overlay going as well and it crashed when it tried to render a red number.

https://pastebin.com/Vw83gY8X

**Comment by McJty** [comment]
Why is the one probe involved in this?

**Comment by McJty** [comment]
I suspect this is a bug in chickenlib btw

**Comment by MokahTGS** [comment]
at mcjty.theoneprobe.rendering.RenderHelper.renderItemStack(RenderHelper.java:451)
    at mcjty.theoneprobe.apiimpl.client.ElementItemStackRender.render(ElementItemStackRender.java:28)
    at mcjty.theoneprobe.apiimpl.elements.ElementItemStack.render(ElementItemStack.java:35)
    at mcjty.theoneprobe.apiimpl.elements.ElementHorizontal.render(ElementHorizontal.java:41)
    at mcjty.theoneprobe.apiimpl.elements.ElementVertical.render(ElementVertical.java:41)
    at mcjty.theoneprobe.rendering.OverlayRenderer.renderElements(OverlayRenderer.java:429)
    at mcjty.theoneprobe.rendering.OverlayRenderer.renderHUDBlock(OverlayRenderer.java:265)
    at mcjty.theoneprobe.rendering.OverlayRenderer.renderHUD(OverlayRenderer.java:117)

**Comment by McJty** [comment]
yes, but the actual crash is above that in chickenlib. Please report to them

**Comment by MokahTGS** [comment]
Will do
