### ISSUE TITLE
Server log stacktrace spam ATM3 v.5.6

### ISSUE THREAD

**Issue by kulflame** [McJty/TheOneProbe#221]
ATM3 Server console spam...  I see a similar issue posted in 2016 that was closed.  This is in Minecraft 1.12.

```
04.01 19:26:12 [Server] Server thread/FATAL Error executing task
04.01 19:26:12 [Server] INFO java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.entity.player.InventoryPlayer.func_70440_f(I)Lnet/minecraft/item/ItemStack;
04.01 19:26:12 [Server] INFO at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_152]
04.01 19:26:12 [Server] INFO at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_152]
04.01 19:26:12 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
04.01 19:26:12 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
04.01 19:26:12 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
04.01 19:26:12 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
04.01 19:26:12 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
04.01 19:26:12 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
04.01 19:26:12 [Server] INFO Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.player.InventoryPlayer.func_70440_f(I)Lnet/minecraft/item/ItemStack;
04.01 19:26:12 [Server] INFO at zmaster587.libVulpes.util.InputSyncHandler.updateKeyPress(InputSyncHandler.java:31) ~[InputSyncHandler.class:unspecified]
04.01 19:26:12 [Server] INFO at zmaster587.libVulpes.network.PacketChangeKeyState.executeServer(PacketChangeKeyState.java:45) ~[PacketChangeKeyState.class:unspecified]
04.01 19:26:12 [Server] INFO at zmaster587.libVulpes.network.BasePacket$BasePacketHandlerServer$executor.run(BasePacket.java:120) ~[BasePacket$BasePacketHandlerServer$executor.class:unspecified]
04.01 19:26:12 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_152]
04.01 19:26:12 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_152]
04.01 19:26:12 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
04.01 19:26:12 [Server] INFO ... 5 more
04.01 19:26:13 [Server] Server thread/FATAL Error executing task
04.01 19:26:13 [Server] INFO java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.entity.player.InventoryPlayer.func_70440_f(I)Lnet/minecraft/item/ItemStack;
04.01 19:26:13 [Server] INFO at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_152]
04.01 19:26:13 [Server] INFO at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_152]
04.01 19:26:13 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
04.01 19:26:13 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
04.01 19:26:13 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
04.01 19:26:13 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
04.01 19:26:13 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
04.01 19:26:13 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
04.01 19:26:13 [Server] INFO Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.player.InventoryPlayer.func_70440_f(I)Lnet/minecraft/item/ItemStack;
04.01 19:26:13 [Server] INFO at zmaster587.libVulpes.util.InputSyncHandler.updateKeyPress(InputSyncHandler.java:31) ~[InputSyncHandler.class:unspecified]
04.01 19:26:13 [Server] INFO at zmaster587.libVulpes.network.PacketChangeKeyState.executeServer(PacketChangeKeyState.java:45) ~[PacketChangeKeyState.class:unspecified]
04.01 19:26:13 [Server] INFO at zmaster587.libVulpes.network.BasePacket$BasePacketHandlerServer$executor.run(BasePacket.java:120) ~[BasePacket$BasePacketHandlerServer$executor.class:unspecified]
04.01 19:26:13 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_152]
04.01 19:26:13 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_152]
04.01 19:26:13 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
04.01 19:26:13 [Server] INFO ... 5 more
04.01 19:26:14 [Server] Server thread/FATAL Error executing task
04.01 19:26:14 [Server] INFO java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.entity.player.InventoryPlayer.func_70440_f(I)Lnet/minecraft/item/ItemStack;
04.01 19:26:14 [Server] INFO at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_152]
04.01 19:26:14 [Server] INFO at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_152]
04.01 19:26:14 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
04.01 19:26:14 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
04.01 19:26:14 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
04.01 19:26:14 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
04.01 19:26:14 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
04.01 19:26:14 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
04.01 19:26:14 [Server] INFO Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.player.InventoryPlayer.func_70440_f(I)Lnet/minecraft/item/ItemStack;
04.01 19:26:14 [Server] INFO at zmaster587.libVulpes.util.InputSyncHandler.updateKeyPress(InputSyncHandler.java:31) ~[InputSyncHandler.class:unspecified]
04.01 19:26:14 [Server] INFO at zmaster587.libVulpes.network.PacketChangeKeyState.executeServer(PacketChangeKeyState.java:45) ~[PacketChangeKeyState.class:unspecified]
04.01 19:26:14 [Server] INFO at zmaster587.libVulpes.network.BasePacket$BasePacketHandlerServer$executor.run(BasePacket.java:120) ~[BasePacket$BasePacketHandlerServer$executor.class:unspecified]
04.01 19:26:14 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_152]
04.01 19:26:14 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_152]
04.01 19:26:14 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
04.01 19:26:14 [Server] INFO ... 5 more
04.01 19:26:15 [Server] Server thread/FATAL Error executing task
04.01 19:26:15 [Server] INFO java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.entity.player.InventoryPlayer.func_70440_f(I)Lnet/minecraft/item/ItemStack;
04.01 19:26:15 [Server] INFO at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_152]
04.01 19:26:15 [Server] INFO at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_152]
04.01 19:26:15 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
04.01 19:26:15 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
04.01 19:26:15 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
04.01 19:26:15 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
04.01 19:26:15 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
04.01 19:26:15 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
04.01 19:26:15 [Server] INFO Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.player.InventoryPlayer.func_70440_f(I)Lnet/minecraft/item/ItemStack;
04.01 19:26:15 [Server] INFO at zmaster587.libVulpes.util.InputSyncHandler.updateKeyPress(InputSyncHandler.java:31) ~[InputSyncHandler.class:unspecified]
04.01 19:26:15 [Server] INFO at zmaster587.libVulpes.network.PacketChangeKeyState.executeServer(PacketChangeKeyState.java:45) ~[PacketChangeKeyState.class:unspecified]
04.01 19:26:15 [Server] INFO at zmaster587.libVulpes.network.BasePacket$BasePacketHandlerServer$executor.run(BasePacket.java:120) ~[BasePacket$BasePacketHandlerServer$executor.class:unspecified]
04.01 19:26:15 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_152]
04.01 19:26:15 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_152]
04.01 19:26:15 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
04.01 19:26:15 [Server] INFO ... 5 more
04.01 19:26:19 [Server] Server thread/WARN Can't keep up! Did the system time change, or is the server overloaded? Running 2218ms behind, skipping 44 tick(s)
```

**Comment by josephcsible** [comment]
Why do you think this is a The One Probe issue? Can you report it to [libVulpes](https://github.com/zmaster587/LibVulpes/issues)?
