### ISSUE TITLE
[1.14.1] java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by Blayyke** [McJty/TheOneProbe#306]
I get the below stacktrace sometimes when i load a world or join a server
```
[20:29:19] [Server thread/FATAL]: Error executing task on Server
java.lang.NullPointerException: null
	at mcjty.theoneprobe.network.ThrowableIdentity.registerThrowable(ThrowableIdentity.java:25) ~[theoneprobe-1.14-1.4.29.beta.jar:?]
	at mcjty.theoneprobe.network.PacketGetInfo.getProbeInfo(PacketGetInfo.java:154) ~[theoneprobe-1.14-1.4.29.beta.jar:?]
	at mcjty.theoneprobe.network.PacketGetInfo.access$600(PacketGetInfo.java:34) ~[theoneprobe-1.14-1.4.29.beta.jar:?]
	at mcjty.theoneprobe.network.PacketGetInfo$Handler.handle(PacketGetInfo.java:117) ~[theoneprobe-1.14-1.4.29.beta.jar:?]
	at mcjty.theoneprobe.network.PacketGetInfo$Handler.handle(PacketGetInfo.java:106) ~[theoneprobe-1.14-1.4.29.beta.jar:?]
	at mcjty.theoneprobe.network.MessageHandler.lambda$accept$0(MessageHandler.java:15) ~[theoneprobe-1.14-1.4.29.beta.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-minecraft-1.14.1-client.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:135) [intermediary-minecraft-1.14.1-client.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-minecraft-1.14.1-client.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:114) [intermediary-minecraft-1.14.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:702) [intermediary-minecraft-1.14.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:696) [intermediary-minecraft-1.14.1-client.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:123) [intermediary-minecraft-1.14.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:681) [intermediary-minecraft-1.14.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:636) [intermediary-minecraft-1.14.1-client.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

```
Full game log: https://gist.github.com/Blayyke/5c9dd4c1f49ca47ec3d3c0ee726b2c13
May be related to be being kicked with the following message on servers: https://i.imgur.com/iBUXQrd.png , however im not sure.

**Comment by Blayyke** [comment]
Okay the kick message is unrelated since i just had it happen then without receiving the previous stacktrace, after getting
```
[21:00:07] [main/ERROR]: Can't ping 178.32.105.168:26673: Timed out
``` 
in console.
