### ISSUE TITLE
The One Probe - Cannot identify spawner settings, returns: Error:theoneprobe:default

### ISSUE THREAD

**Issue by Kolerath** [McJty/TheOneProbe#323]
When running a MP server, the one probe mod cannot identify the settings on Monster Spawner blocks for clients. 
It just returns "Error:theoneprobe:default" and the server log returns:

[18:53:05] [Server thread/DEBUG] [theoneprobe]: The One Probe catched error:
java.lang.NoSuchMethodError: net.minecraft.tileentity.MobSpawnerBaseLogic.func_184994_d()Lnet/minecraft/entity/Entity;
at mcjty.theoneprobe.apiimpl.providers.DefaultProbeInfoProvider.showMobSpawnerInfo(DefaultProbeInfoProvider.java:127) ~[DefaultProbeInfoProvider.class:?]
at mcjty.theoneprobe.apiimpl.providers.DefaultProbeInfoProvider.addProbeInfo(DefaultProbeInfoProvider.java:101) ~[DefaultProbeInfoProvider.class:?]
at mcjty.theoneprobe.network.PacketGetInfo.getProbeInfo(PacketGetInfo.java:144) ~[PacketGetInfo.class:?]
at mcjty.theoneprobe.network.PacketGetInfo.access$600(PacketGetInfo.java:34) ~[PacketGetInfo.class:?]
at mcjty.theoneprobe.network.PacketGetInfo$Handler.handle(PacketGetInfo.java:109) ~[PacketGetInfo$Handler.class:?]
at mcjty.theoneprobe.network.PacketGetInfo$Handler.lambda$onMessage$0(PacketGetInfo.java:102) ~[PacketGetInfo$Handler.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_211]
at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_211]
at net.minecraft.util.Util.runTask(SourceFile:529) [h.class:?]
at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]

-----------------------------------

Strangely enough this doesn't happen on SP servers, only in MP Servers.

I've tested with 2 clients on my MP server and I am getting the same error on both.

**Comment by McJty** [comment]
Version please?

**Comment by Kolerath** [comment]
Hello McJty,

The version is: 1.12-1.4.28
