### ISSUE TITLE
[1.14-1.4.35-alpha] Client crash when looking at the fox

### ISSUE THREAD

**Issue by ImperatorEdi** [McJty/TheOneProbe#327]
Describe what you were doing before the crash:
Looking the fox with any type of item crash client. Server still work fine (no errors and warnings).

VERSION MC: 1.14.4
VERSION Forge: 28.1.0
VERSION Mod: 1.14-1.4.35-alpha

Crash Log
`---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 22.09.19 21:31
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
at net.minecraft.entity.ai.goal.PrioritizedGoal.hashCode(SourceFile:93) ~[?:?] {}
at java.util.HashMap.hash(HashMap.java:338) ~[?:1.8.0_51] {}
at java.util.HashMap.put(HashMap.java:611) ~[?:1.8.0_51] {}
at java.util.HashSet.add(HashSet.java:219) ~[?:1.8.0_51] {}
at net.minecraft.entity.ai.goal.GoalSelector.func_75776_a(SourceFile:44) ~[?:?] {}
at net.minecraft.entity.passive.FoxEntity.func_213501_ej(FoxEntity.java:301) ~[?:?] {}
at net.minecraft.entity.passive.FoxEntity.func_213386_a(FoxEntity.java:294) ~[?:?] {}
at net.minecraft.entity.EntityType.func_220349_b(EntityType.java:319) ~[?:?] {}
at mcjty.theoneprobe.apiimpl.client.ElementEntityRender.render(ElementEntityRender.java:34) ~[?:?] {}
at mcjty.theoneprobe.apiimpl.elements.ElementEntity.render(ElementEntity.java:71) ~[?:?] {}
at mcjty.theoneprobe.apiimpl.elements.ElementHorizontal.render(ElementHorizontal.java:41) ~[?:?] {}
at mcjty.theoneprobe.apiimpl.elements.ElementVertical.render(ElementVertical.java:41) ~[?:?] {}
at mcjty.theoneprobe.rendering.OverlayRenderer.renderElements(OverlayRenderer.java:431) ~[?:?] {}
at mcjty.theoneprobe.rendering.OverlayRenderer.renderHUDEntity(OverlayRenderer.java:184) ~[?:?] {}
at mcjty.theoneprobe.rendering.OverlayRenderer.renderHUD(OverlayRenderer.java:82) ~[?:?] {}
at mcjty.theoneprobe.proxy.ClientProxy.renderGameOverlayEvent(ClientProxy.java:114) ~[?:?] {}
at net.minecraftforge.eventbus.ASMEventHandler_442_ClientProxy_renderGameOverlayEvent_Pre.invoke(.dynamic) ~[?:?] {}
at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?] {}
at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
at net.minecraftforge.client.ForgeIngameGui.renderHUDText(ForgeIngameGui.java:637) ~[?:?] {}
at net.minecraftforge.client.ForgeIngameGui.func_175180_a(ForgeIngameGui.java:186) ~[?:?] {}
at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:520) ~[?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:887) [?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.client.main.Main.main(SourceFile:155) [?:?] {}
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.1.0.jar:28.1] {}
at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$348/1773008684.call(Unknown Source) [forge-1.14.4-28.1.0.jar:28.1] {}
at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-3.2.0.jar:?] {}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50) [modlauncher-3.2.0.jar:?] {}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:68) [modlauncher-3.2.0.jar:?] {}
at cpw.mods.modlauncher.Launcher.run(Launcher.java:80) [modlauncher-3.2.0.jar:?] {}
at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-3.2.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
-- Head --
Thread: Client thread
Stacktrace:
at net.minecraft.entity.ai.goal.PrioritizedGoal.hashCode(SourceFile:93)
at java.util.HashMap.hash(HashMap.java:338)
at java.util.HashMap.put(HashMap.java:611)
at java.util.HashSet.add(HashSet.java:219)
at net.minecraft.entity.ai.goal.GoalSelector.func_75776_a(SourceFile:44)
at net.minecraft.entity.passive.FoxEntity.func_213501_ej(FoxEntity.java:301)
at net.minecraft.entity.passive.FoxEntity.func_213386_a(FoxEntity.java:294)
at net.minecraft.entity.EntityType.func_220349_b(EntityType.java:319)
at mcjty.theoneprobe.apiimpl.client.ElementEntityRender.render(ElementEntityRender.java:34)
at mcjty.theoneprobe.apiimpl.elements.ElementEntity.render(ElementEntity.java:71)
at mcjty.theoneprobe.apiimpl.elements.ElementHorizontal.render(ElementHorizontal.java:41)
at mcjty.theoneprobe.apiimpl.elements.ElementVertical.render(ElementVertical.java:41)
at mcjty.theoneprobe.rendering.OverlayRenderer.renderElements(OverlayRenderer.java:431)
at mcjty.theoneprobe.rendering.OverlayRenderer.renderHUDEntity(OverlayRenderer.java:184)
at mcjty.theoneprobe.rendering.OverlayRenderer.renderHUD(OverlayRenderer.java:82)
at mcjty.theoneprobe.proxy.ClientProxy.renderGameOverlayEvent(ClientProxy.java:114)
at net.minecraftforge.eventbus.ASMEventHandler_442_ClientProxy_renderGameOverlayEvent_Pre.invoke(.dynamic)
at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
at net.minecraftforge.client.ForgeIngameGui.renderHUDText(ForgeIngameGui.java:637)
at net.minecraftforge.client.ForgeIngameGui.func_175180_a(ForgeIngameGui.java:186)

-- Affected level --
Details:
All players: 1 total; [ClientPlayerEntity['Imperator_Edi'/1074, l='MpServer', x=-224.96, y=65.49, z=241.63]]
Chunk stats: Client Chunk Cache: 729, 497
Level dimension: DimensionType{minecraft:overworld}
Level name: MpServer
Level seed: 0
Level generator: ID 09 - biomesoplenty, ver 0. Features enabled: false
Level generator options: {}
Level spawn location: World: (-96,71,112), Chunk: (at 0,4,0 in -6,7; contains blocks -96,0,112 to -81,255,127), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Level time: 2119724 game time, 482023 day time
Level storage version: 0x00000 - Unknown?
Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Server brand: forge
Server type: Non-integrated multiplayer server
Stacktrace:
at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:410)
at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1747)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:405)
at net.minecraft.client.main.Main.main(SourceFile:155)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$348/1773008684.call(Unknown Source)
at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50)
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:68)
at cpw.mods.modlauncher.Launcher.run(Launcher.java:80)
at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
Minecraft Version: 1.14.4
Minecraft Version ID: 1.14.4
Operating System: Windows 8.1 (amd64) version 6.3
Java Version: 1.8.0_51, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 576950112 bytes (550 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
CPUs: 4
JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
ModLauncher: 3.2.0+60+b86c1d4
ModLauncher launch target: fmlclient
ModLauncher naming: srg
ModLauncher services:
/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE
/forge-1.14.4-28.1.0.jar object_holder_definalize PLUGINSERVICE
/forge-1.14.4-28.1.0.jar runtime_enum_extender PLUGINSERVICE
/accesstransformers-1.0.0-shadowed.jar accesstransformer PLUGINSERVICE
/forge-1.14.4-28.1.0.jar capability_inject_definalize PLUGINSERVICE
/forge-1.14.4-28.1.0.jar runtimedistcleaner PLUGINSERVICE
/forge-1.14.4-28.1.0.jar fml TRANSFORMATIONSERVICE
FML: 28.1
Forge: net.minecraftforge:28.1.0
FML Language Providers:
javafml@28.1
minecraft@1
Mod List:
[1.14.4]+SecurityCraft+v1.8.12.3.jar SecurityCraft {securitycraft@v1.8.12.3 DONE}
alchemistry-1.14.4-3.jar Alchemistry {alchemistry@1.14.4-3 DONE}
alib-1.14.4-4.jar A Lib {alib@1.14.4-4 DONE}
betteranimalsplus-1.14.4-7.1.2.jar Better Animals Plus {betteranimalsplus@7.1.2 DONE}
BiomesOPlenty-1.14.4-9.0.0.247-universal.jar Biomes O' Plenty {biomesoplenty@1.14.4-9.0.0.247 DONE}
Bookshelf-1.14.4-4.2.48.jar Bookshelf {bookshelf@4.2.48 DONE}
CarryOn+MC1.14.4+v1.12.3.jar Carry On {carryon@1.12.3 DONE}
cc-tweaked-1.14.4-1.84.1.jar CC: Tweaked {computercraft@1.84.1 DONE}
chemlib-1.14.4-4.jar Chem Lib {chemlib@1.14.4-4 DONE}
create-mc1.14.4_v0.1.0.jar Create {create@0.1.0 DONE}
curios-FORGE-1.14.4-1.0.0.1.jar Curios API {curios@FORGE-1.14.4-1.0.0.1 DONE}
damage_indicator-0.0.7.jar Ama's Damage Indicator {damage_indicator@0.0.7 DONE}
dankstorage-1.2a.jar Dank Storage {dankstorage@1.2a DONE}
EasySteel-1.14.4-1.0.13.jar Easy Steel {easy_steel@1.0.13 DONE}
engineersdecor-1.14.4-1.0.12-b2.jar Engineer's Decor {engineersdecor@1.0.12-b2 DONE}
engineerstools-1.14.4-1.0.3-b2.jar Engineer's Tools {engineerstools@1.0.3-b2 DONE}
exp_bottling-1.14.4-3.jar EXP Bottling {exp_bottling@1.14.4-3 DONE}
extcaves-1.2.jar Extended Caves {extcaves@1.2 DONE}
Floocraft+1.14.4-1.9.7.jar Floocraft {floocraftft@1.9.7 DONE}
furniture-7.0.0-pre8-1.14.4.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre8 DONE}
GameStages-1.14.4-4.2.14.jar GameStages {gamestages@4.2.14 DONE}
gates-1.2.0.jar Gates {gates@1.2.0 DONE}
gravestone-1.15.1.jar Gravestone Mod {gravestone@1.15.1 DONE}
ironchest-1.14.4-9.1.5.jar Iron Chests {ironchest@1.14.3-9.0.3 DONE}
ironshulkerboxes-1.14.4-3.1.12.jar Iron Shulker Boxes {ironshulkerbox@1.14.4-3.1.12 DONE}
jei-1.14.4-6.0.0.12.jar Just Enough Items {jei@6.0.0.12 DONE}
LLOverlayReloaded-1.2.4-mc1.14.4.jar Light Level Overlay Reloaded {llor@1.2.4-mc1.14.4 DONE}
MCAdditions-1.2.0.jar MCA {mca@0.0.1 DONE}
mcjtylib-1.14-3.5.7-alpha.jar McJtyLib {mcjtylib@NONE DONE}
mcpaint-1.4.4.jar Mc Paint {mcpaint@1.4.4 DONE}
modnametooltip_1.14.3-1.12.1.jar Mod Name Tooltip {modnametooltip@1.12.1 DONE}
moreboots-1.1.6.jar More Boots {moreboots@1.1.6 DONE}
PowderPower-1.14.4-3.0.18.jar Powder Power {powder_power@3.0.18 DONE}
practicaltools-1.14.4-1.4.jar Practical Tools {practicaltools@1.14.4-1.4 DONE}
quickhomes-1.14.4-1.2.4.2.jar QuickHomes {quickhomes@1.2.4.2 DONE}
restrictions-1.14-1.3.4-alpha.jar Restrictions {restrictions@NONE DONE}
rsgauges-1.14.4-1.1.8-b3.jar Redstone Gauges and Switches {rsgauges@1.1.8-b3 DONE}
SilentLib-1.14.4-4.4.0+44.jar Silent Lib {silentlib@4.4.0+44 DONE}
SilentMechanisms-1.14.4-0.5.2+28.jar Silent's Mechanisms {silents_mechanisms@0.5.2+28 DONE}
SimpleDivingGear-3.0.1+mc+1.14.4.jar Simple Diving Gear {simpledivegear@3.0.1 mc 1.14.4 DONE}
StorageDrawers-1.14.4-6.0.5.jar Storage Drawers {storagedrawers@1.14.4-6.0.3 DONE}
structurize-0.10.167-ALPHA.jar Structurize {structurize@unspecified DONE}
minecolonies-0.10.379-ALPHA-universal.jar Minecolonies {minecolonies@1 DONE}
The-One-Probe-Mod-1.14.4.jar The One Probe {theoneprobe@NONE DONE}
travel_bag-1.0.5-1.14.4.jar Travel Bag {travel_bag@1.0.5 DONE}
ultra_amplified_mod-1.14.4-0.6.7.jar Ultra Amplified Mod {ultra_amplified_mod@0.6.7 DONE}
UselessMod-1.14.4-2.2.4.jar Useless Mod {uselessmod@1.14.4-2.2.4 DONE}
Xaeros_Minimap_1.18.1.1_Forge_1.14.4.jar Xaero's Minimap {xaerominimap@1.18.1.1 DONE}
forge-1.14.4-28.1.0-universal.jar Forge {forge@28.1.0 DONE}
goprone-1.14.x-1.0.3.jar GoProne {goprone@1.14.x-1.0.3 DONE}
forge-1.14.4-28.1.0-client.jar Minecraft {minecraft@1.14.4 DONE}
Launched Version: 1.14.4-forge-28.1.0
LWJGL: 3.2.2 build 10
OpenGL: Intel(R) HD Graphics 4400 GL version 4.3.0 - Build 10.18.14.4414, Intel
GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'forge'
Type: Client (map_client.txt)
Resource Packs: 
Current Language: 
CPU: 4x Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz`

**Comment by McJty** [comment]
Can you show me the filename for your theoneprobe mod jar?

**Comment by ImperatorEdi** [comment]
https://www.curseforge.com/minecraft/mc-mods/the-one-probe/files/2790544

I downloaded this version and pasted it into the mods directory without renaming it.

**Comment by McJty** [comment]
Very weird. I have fixed the fox bug some time ago. I have to check what went wrong

**Comment by ImperatorEdi** [comment]
This is The-One-Probe-Mod-1.14.4.jar but on CF is another name.

I'm sorry, I don't know where or why I have this version of mod. I'll check your latest curseforge version tonight and let you know.

I wonder where I got it from when I'm only taking a modification from a curseforge?

**Comment by McJty** [comment]
It is probably a problem on my side though. I'll have to check this evening

**Comment by McJty** [comment]
Is this problem still present with the latest version that I released today?

**Comment by ImperatorEdi** [comment]
No, any problems.
