### ISSUE TITLE
"/topcfg setpos" doesn't work

### ISSUE THREAD

**Issue by feldim2425** [McJty/TheOneProbe#33]
if I write for example: "/topcfg setpos 1 1 100 100" it does nothing
and if there is one argument less (like  "/topcfg setpos 1 1 100") it throws an exception:

```
18:06:05] [Client thread/WARN]: Couldn't process command: 'topcfg setpos 1 1 100'
java.lang.ArrayIndexOutOfBoundsException: 4
	at mcjty.theoneprobe.commands.CommandTopCfg.setPos(CommandTopCfg.java:66) ~[CommandTopCfg.class:?]
	at mcjty.theoneprobe.commands.CommandTopCfg.func_184881_a(CommandTopCfg.java:88) ~[CommandTopCfg.class:?]
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:103) [k.class:?]
	at net.minecraftforge.client.ClientCommandHandler.func_71556_a(ClientCommandHandler.java:92) [ClientCommandHandler.class:?]
	at net.minecraft.client.gui.GuiScreen.func_175281_b(GuiScreen.java:437) [bft.class:?]
	at net.minecraft.client.gui.GuiScreen.func_175275_f(GuiScreen.java:428) [bft.class:?]
	at net.minecraft.client.gui.GuiChat.func_73869_a(SourceFile:81) [bew.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:571) [bft.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:525) [bft.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1700) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:282) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:364) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
```

**Comment by McJty** [comment]
Fixed next release
