### ISSUE TITLE
Looking at painting cause massive lag

### ISSUE THREAD

**Issue by momosundeass** [McJty/TheOneProbe#380]
full debug.log https://drive.google.com/file/d/1-92K2zKQ_ETMvXL2dXYScK1QBpTXCZin/view

minecraft 1.15.2
forge-1.15.2-31.1.63
mod version 1.15.2.0.2

```
[29Apr2020 15:59:19.913] [Render thread/ERROR] [mcjty.theoneprobe.TheOneProbe/]: Error rendering entity!
net.minecraft.crash.ReportedException: Rendering entity in world
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:273) ~[?:?]
	at mcjty.theoneprobe.rendering.RenderHelper.renderEntity(RenderHelper.java:62) [?:1.15-2.0.2]
	at mcjty.theoneprobe.apiimpl.client.ElementEntityRender.renderEntity(ElementEntityRender.java:163) [?:1.15-2.0.2]
	at mcjty.theoneprobe.apiimpl.client.ElementEntityRender.render(ElementEntityRender.java:52) [?:1.15-2.0.2]
	at mcjty.theoneprobe.apiimpl.elements.ElementEntity.render(ElementEntity.java:67) [?:1.15-2.0.2]
	at mcjty.theoneprobe.apiimpl.elements.ElementHorizontal.render(ElementHorizontal.java:41) [?:1.15-2.0.2]
	at mcjty.theoneprobe.apiimpl.elements.ElementVertical.render(ElementVertical.java:41) [?:1.15-2.0.2]
	at mcjty.theoneprobe.rendering.OverlayRenderer.renderElements(OverlayRenderer.java:437) [?:1.15-2.0.2]
	at mcjty.theoneprobe.rendering.OverlayRenderer.renderHUDBlock(OverlayRenderer.java:261) [?:1.15-2.0.2]
	at mcjty.theoneprobe.rendering.OverlayRenderer.renderHUD(OverlayRenderer.java:117) [?:1.15-2.0.2]
	at mcjty.theoneprobe.proxy.ClientProxy.renderGameOverlayEvent(ClientProxy.java:110) [?:1.15-2.0.2]
	at net.minecraftforge.eventbus.ASMEventHandler_613_ClientProxy_renderGameOverlayEvent_Pre.invoke(.dynamic) [?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) [eventbus-2.1.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) [eventbus-2.1.0-service.jar:?]
	at net.minecraftforge.client.gui.ForgeIngameGui.renderHUDText(ForgeIngameGui.java:636) [?:?]
	at net.minecraftforge.client.gui.ForgeIngameGui.func_175180_a(ForgeIngameGui.java:186) [?:?]
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:460) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:924) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553) [?:?]
	at net.minecraft.client.main.Main.main(SourceFile:204) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.2-31.1.63.jar:31.1]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$462/194318210.call(Unknown Source) [forge-1.15.2-31.1.63.jar:31.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.client.renderer.entity.PaintingRenderer.func_225623_a_(SourceFile:41) ~[?:?]
	at net.minecraft.client.renderer.entity.PaintingRenderer.func_225623_a_(SourceFile:23) ~[?:?]
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:245) ~[?:?]
	... 30 more
```

[edit] clean up debug.log

**Comment by McJty** [comment]
Version number?

**Comment by momosundeass** [comment]
edited

**Comment by McJty** [comment]
Hmm, I cannot reproduce this problem. Maybe it's caused by some other mod messing with paintings?

**Comment by momosundeass** [comment]
It may cause by resource pack
let me check

**Comment by McJty** [comment]
Ah never mind. I can reproduce it

**Comment by McJty** [comment]
I fixed it. Will be ok next release

**Comment by momosundeass** [comment]
thank you :D
