### ISSUE TITLE
[1.15.2]Client crashed when enchanting the helmet_probe by anvil

### ISSUE THREAD

**Issue by gloomybanana** [McJty/TheOneProbe#397]
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 20-7-16 下午5:20
Description: mouseClicked event handler

java.lang.NullPointerException: mouseClicked event handler
	at net.minecraft.item.ArmorItem.getIsRepairable(ArmorItem.java:76) ~[forge-1.15.2-31.2.23_mapped_snapshot_20200624-1.15.1.jar:?] {re:classloading}
	at net.minecraft.inventory.container.RepairContainer.updateRepairOutput(RepairContainer.java:142) ~[forge-1.15.2-31.2.23_mapped_snapshot_20200624-1.15.1.jar:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.inventory.container.RepairContainer.onCraftMatrixChanged(RepairContainer.java:117) ~[forge-1.15.2-31.2.23_mapped_snapshot_20200624-1.15.1.jar:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.inventory.container.RepairContainer$1.markDirty(RepairContainer.java:32) ~[forge-1.15.2-31.2.23_mapped_snapshot_20200624-1.15.1.jar:?] {re:classloading}
	at net.minecraft.inventory.Inventory.setInventorySlotContents(SourceFile:117) ~[forge-1.15.2-31.2.23_mapped_snapshot_20200624-1.15.1.jar:?] {re:classloading}
	at net.minecraft.inventory.container.Slot.putStack(Slot.java:61) ~[forge-1.15.2-31.2.23_mapped_snapshot_20200624-1.15.1.jar:?] {re:classloading}
	at net.minecraft.inventory.container.Container.mergeItemStack(Container.java:525) ~[forge-1.15.2-31.2.23_mapped_snapshot_20200624-1.15.1.jar:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.inventory.container.RepairContainer.transferStackInSlot(RepairContainer.java:322) ~[forge-1.15.2-31.2.23_mapped_snapshot_20200624-1.15.1.jar:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.inventory.container.Container.slotClick(Container.java:231) ~[forge-1.15.2-31.2.23_mapped_snapshot_20200624-1.15.1.jar:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.multiplayer.PlayerController.windowClick(PlayerController.java:374) ~[forge-1.15.2-31.2.23_mapped_snapshot_20200624-1.15.1.jar:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.handleMouseClick(ContainerScreen.java:503) ~[forge-1.15.2-31.2.23_mapped_snapshot_20200624-1.15.1.jar:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.mouseClicked(ContainerScreen.java:316) ~[forge-1.15.2-31.2.23_mapped_snapshot_20200624-1.15.1.jar:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:82) ~[forge-1.15.2-31.2.23_mapped_snapshot_20200624-1.15.1.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:446) ~[forge-1.15.2-31.2.23_mapped_snapshot_20200624-1.15.1.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.mouseButtonCallback(MouseHelper.java:80) ~[forge-1.15.2-31.2.23_mapped_snapshot_20200624-1.15.1.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:163) ~[forge-1.15.2-31.2.23_mapped_snapshot_20200624-1.15.1.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94) ~[forge-1.15.2-31.2.23_mapped_snapshot_20200624-1.15.1.jar:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:162) ~[forge-1.15.2-31.2.23_mapped_snapshot_20200624-1.15.1.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:105) ~[forge-1.15.2-31.2.23_mapped_snapshot_20200624-1.15.1.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MainWindow.flipFrame(MainWindow.java:296) ~[forge-1.15.2-31.2.23_mapped_snapshot_20200624-1.15.1.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:946) ~[forge-1.15.2-31.2.23_mapped_snapshot_20200624-1.15.1.jar:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.run(Minecraft.java:553) ~[forge-1.15.2-31.2.23_mapped_snapshot_20200624-1.15.1.jar:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) ~[forge-1.15.2-31.2.23_mapped_snapshot_20200624-1.15.1.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_251] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_251] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_251] {}
	at net.minecraftforge.userdev.FMLUserdevClientLaunchProvider.lambda$launchService$0(FMLUserdevClientLaunchProvider.java:55) ~[forge-1.15.2-31.2.23_mapped_snapshot_20200624-1.15.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {}
	at net.minecraftforge.userdev.LaunchTesting.main(LaunchTesting.java:105) [forge-1.15.2-31.2.23_mapped_snapshot_20200624-1.15.1.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.item.ArmorItem.getIsRepairable(ArmorItem.java:76)
	at net.minecraft.inventory.container.RepairContainer.updateRepairOutput(RepairContainer.java:142)
	at net.minecraft.inventory.container.RepairContainer.onCraftMatrixChanged(RepairContainer.java:117)
	at net.minecraft.inventory.container.RepairContainer$1.markDirty(RepairContainer.java:32)
	at net.minecraft.inventory.Inventory.setInventorySlotContents(SourceFile:117)
	at net.minecraft.inventory.container.Slot.putStack(Slot.java:61)
	at net.minecraft.inventory.container.Container.mergeItemStack(Container.java:525)
	at net.minecraft.inventory.container.RepairContainer.transferStackInSlot(RepairContainer.java:322)
	at net.minecraft.inventory.container.Container.slotClick(Container.java:231)
	at net.minecraft.client.multiplayer.PlayerController.windowClick(PlayerController.java:374)
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.handleMouseClick(ContainerScreen.java:503)
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.mouseClicked(ContainerScreen.java:316)
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:82)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.screen.inventory.AnvilScreen
Stacktrace:
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:446)
	at net.minecraft.client.MouseHelper.mouseButtonCallback(MouseHelper.java:80)
	at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:163)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94)
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:162)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:105)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Dev'/172, l='MpServer', x=-196.25, y=64.00, z=95.30]]
	Chunk stats: Client Chunk Cache: 841, 575
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: -7993131286122441621
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-192,83,80), Chunk: (at 0,5,0 in -12,5; contains blocks -192,0,80 to -177,255,95), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 2266 game time, 2266 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.fillCrashReport(ClientWorld.java:442)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:1763)
	at net.minecraft.client.Minecraft.run(Minecraft.java:567)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.userdev.FMLUserdevClientLaunchProvider.lambda$launchService$0(FMLUserdevClientLaunchProvider.java:55)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
	at net.minecraftforge.userdev.LaunchTesting.main(LaunchTesting.java:105)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_251, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 438551448 bytes (418 MB) / 996671488 bytes (950 MB) up to 1901592576 bytes (1813 MB)
	CPUs: 8
	JVM Flags: 1 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmluserdevclient
	ModLauncher naming: mcp
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.23_mapped_snapshot_20200624-1.15.1-launcher.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.23_mapped_snapshot_20200624-1.15.1-launcher.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.23_mapped_snapshot_20200624-1.15.1-launcher.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.23_mapped_snapshot_20200624-1.15.1-launcher.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.2.23_mapped_snapshot_20200624-1.15.1-launcher.jar fml TRANSFORMATIONSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.23
	FML Language Providers: 
		javafml@31.2
		minecraft@1
	Mod List: 
		client-extra.jar Minecraft {minecraft@1.15.2 DONE}
		main The One Probe {theoneprobe@NONE DONE}
		forge-1.15.2-31.2.23_mapped_snapshot_20200624-1.15.1.jar Forge {forge@31.2.23 DONE}
	Launched Version: MOD_DEV
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 445.87, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: 简体中文 (中国)
	CPU: 8x Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz

**Comment by ghost** [comment]
This is the result to using TheOneProbe only?

Please test the mod on your Server only.
Maybe it's " Lambda mod " .

**Comment by ghost** [comment]
If you using server wizt mods.
Make sure you have instaled the right forge version.
For server stable versions anytime use the version with the star. 1.15.2-31.2.0 ☆

**Comment by gloomybanana** [comment]
> This is the result to using TheOneProbe only?
> 
> Please test the mod on your Server only.
> Maybe it's " Lambda mod " .

yes，result to using Theoneprob only。
Only the client crashed，
the physic server didn't crash。

**Comment by ghost** [comment]
What version of the one probe you have downloaded.

**Comment by gloomybanana** [comment]
> What version of the one probe you have downloaded.

I build it from the latest 1.15.2 branch code on github..and run it in intelij idea

**Comment by ghost** [comment]
Wait any time. I'll build a testserver.

**Comment by ghost** [comment]
Are you whant debug your plugin or load normaly server?

**Comment by ghost** [comment]
@McJty

OK - This is the fakt.

The mouse button to set any book in the Anvil has got a mistake.
You can pickup the book, but not drop in the field of an Anvil.


**java.lang.NullPointerException: mouseReleased event handler
for
net.minecraft.client.gui.screen.inventory.AnvilScreen**

[[1;31m[12:59:42] [Netty Server IO #3/ERROR] [minecraft/ArgumentTypes]: Could not serialize **net.minecraftforge.server.command.ModIdArgument@4805e46a** 
(class net.minecraftforge.server.command.ModIdArgument) - will not be sent to client!

[[1;31m[12:59:43] [Netty Server IO #3/ERROR] [minecraft/ArgumentTypes]: Could not serialize **net.minecraftforge.server.command.EnumArgument@79fcbb94** 
(class net.minecraftforge.server.command.EnumArgument) - will not be sent to client!

**Comment by Gunner76th** [comment]
Just to let you know, this issue still exists in 1.16.5 
theoneprobe-1.16-3.0.7.jar 
[crash-2021-04-22_14.27.50-client.txt](https://github.com/McJtyMods/TheOneProbe/files/6355500/crash-2021-04-22_14.27.50-client.txt)

**Comment by ShadowJonathan** [comment]
Can concur this still happens, just crashed on direwolf20's modpack (version 1.10.1)

**Comment by RtHiaHB** [comment]
This issue still persists in 1.17.1.  Happened to me twice before I figured out what was going on.  :(

ETA: I'm using version 1.17/4.0.2
