### ISSUE TITLE
Unclear error on 1.21

### ISSUE THREAD

**Issue by moonfather1** [McJty/TheOneProbe#647]
Error:
red text saying it can't get the item name

Versions:
minecraft 1.21, neoforge 21.0.20, top 12.0.0

Steps:
superflat will do, take 2 item frames, 2 cobblestone blocks and 2 shovels from creative inventory.
make a cobblestone pillar, put two item frames on it.
take one shovel, dig out a few grass blocks and then put them back.
put both shovels into item frames.
undamaged one is fine (unrelated, the item frame has some weird rotation in probe's panel, does not look good).
damaged one, when hovered, shows red text and prints out below text in log.

Log:

```
[11:28:12] [Render thread/DEBUG] [mc.th.TheOneProbe/]: The One Probe catched error: 
java.lang.IllegalStateException: Not building!
	at TRANSFORMER/minecraft@1.21/com.mojang.blaze3d.vertex.BufferBuilder.ensureBuilding(BufferBuilder.java:68) ~[neoforge-minecraft-joined-local-merged.jar%23184!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/com.mojang.blaze3d.vertex.BufferBuilder.beginVertex(BufferBuilder.java:89) ~[neoforge-minecraft-joined-local-merged.jar%23184!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/com.mojang.blaze3d.vertex.BufferBuilder.addVertex(BufferBuilder.java:144) ~[neoforge-minecraft-joined-local-merged.jar%23184!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/com.mojang.blaze3d.vertex.VertexConsumer.addVertex(VertexConsumer.java:161) ~[neoforge-minecraft-joined-local-merged.jar%23184!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at TRANSFORMER/theoneprobe@1.21_neo-12.0.0/mcjty.theoneprobe.rendering.RenderHelper.draw(RenderHelper.java:266) ~[the-one-probe-245211-5431197.jar%23188!/:1.21_neo-12.0.0] {re:classloading}
	at TRANSFORMER/theoneprobe@1.21_neo-12.0.0/mcjty.theoneprobe.rendering.RenderHelper.renderItemStackOverlay(RenderHelper.java:243) ~[the-one-probe-245211-5431197.jar%23188!/:1.21_neo-12.0.0] {re:classloading}
	at TRANSFORMER/theoneprobe@1.21_neo-12.0.0/mcjty.theoneprobe.rendering.RenderHelper.renderItemStack(RenderHelper.java:185) ~[the-one-probe-245211-5431197.jar%23188!/:1.21_neo-12.0.0] {re:classloading}
	at TRANSFORMER/theoneprobe@1.21_neo-12.0.0/mcjty.theoneprobe.apiimpl.client.ElementItemStackRender.render(ElementItemStackRender.java:30) ~[the-one-probe-245211-5431197.jar%23188!/:1.21_neo-12.0.0] {re:classloading}
	at TRANSFORMER/theoneprobe@1.21_neo-12.0.0/mcjty.theoneprobe.apiimpl.elements.ElementItemStack.render(ElementItemStack.java:38) ~[the-one-probe-245211-5431197.jar%23188!/:1.21_neo-12.0.0] {re:classloading}
	at TRANSFORMER/theoneprobe@1.21_neo-12.0.0/mcjty.theoneprobe.apiimpl.elements.ElementHorizontal.render(ElementHorizontal.java:56) ~[the-one-probe-245211-5431197.jar%23188!/:1.21_neo-12.0.0] {re:classloading}
	at TRANSFORMER/theoneprobe@1.21_neo-12.0.0/mcjty.theoneprobe.apiimpl.elements.ElementVertical.render(ElementVertical.java:57) ~[the-one-probe-245211-5431197.jar%23188!/:1.21_neo-12.0.0] {re:classloading}
	at TRANSFORMER/theoneprobe@1.21_neo-12.0.0/mcjty.theoneprobe.rendering.OverlayRenderer.renderElements(OverlayRenderer.java:455) ~[the-one-probe-245211-5431197.jar%23188!/:1.21_neo-12.0.0] {re:classloading}
	at TRANSFORMER/theoneprobe@1.21_neo-12.0.0/mcjty.theoneprobe.rendering.OverlayRenderer.renderHUDBlock(OverlayRenderer.java:301) ~[the-one-probe-245211-5431197.jar%23188!/:1.21_neo-12.0.0] {re:classloading}
	at TRANSFORMER/theoneprobe@1.21_neo-12.0.0/mcjty.theoneprobe.rendering.OverlayRenderer.renderHUD(OverlayRenderer.java:128) ~[the-one-probe-245211-5431197.jar%23188!/:1.21_neo-12.0.0] {re:classloading}
	at TRANSFORMER/theoneprobe@1.21_neo-12.0.0/mcjty.theoneprobe.rendering.ClientSetup.renderGameOverlayEvent(ClientSetup.java:79) ~[the-one-probe-245211-5431197.jar%23188!/:1.21_neo-12.0.0] {re:classloading}
```

**Comment by McJty** [comment]
I'll check this out

**Comment by McJty** [comment]
Should be fixed
