### ISSUE TITLE
When the Probe is waiting for a server，the client will be severely stuck

### ISSUE THREAD

**Issue by FortyTwoCn** [McJty/TheOneProbe#656]
![Cache_-526cca6899c3d26b](https://github.com/user-attachments/assets/8718b45a-400d-445a-bf66-ca7285681e81)

When the Probe is waiting for a server, the client will be severely stuck.
This bug will make my CPU usage 100% ,and I hope you can fix this bug.
Thanks!
TheOneProbe - 1.16-3.1.7

**Comment by McJty** [comment]
Well I no longer work on 1.16 but this bug is weird though. I have never had this reported before and TOP is used a lot. So I guess something else must be going on

**Comment by FortyTwoCn** [comment]
> Well I no longer work on 1.16 but this bug is weird though. I have never had this reported before and TOP is used a lot. So I guess something else must be going on

It may be a network issue, but it shouldn't have a stuttering problem

**Comment by McJty** [comment]
Normally when you get this problem you should be able to continue on the client. If you can't I think some other mod is blocking. i.e. TOP is just showing that there is a problem but it is not causing the lag on the client. At least, that's the theory

**Comment by FortyTwoCn** [comment]
![ab93a6869a187d6ea0da303f46d442ea](https://github.com/user-attachments/assets/960688b1-8a35-4f55-8718-b886f850f5c6)

https://github.com/user-attachments/assets/f05ca17f-e774-4312-9fc1-85fc8a0ee3fc

**Comment by FortyTwoCn** [comment]
May be Overflow?

**Comment by FortyTwoCn** [comment]
![0908c57d792aec0909d38f7602d6655e](https://github.com/user-attachments/assets/037aed09-7aba-441c-8d26-d760a7d8a325)

**Comment by FortyTwoCn** [comment]
[19十月2024 20:49:19.428] [Render thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Client
io.netty.handler.codec.DecoderException: The received encoded string buffer length is longer than maximum allowed (1214906 > 131068)
	at net.minecraft.network.PacketBuffer.func_150789_c(PacketBuffer.java:336) ~[?:?]
	at net.minecraft.network.PacketBuffer.func_192575_l(PacketBuffer.java:366) ~[?:?]
	at net.minecraftforge.common.extensions.IForgePacketBuffer.readRegistryId(IForgePacketBuffer.java:98) ~[forge:?]
	at mekanism.api.chemical.gas.GasStack.readFromPacket(GasStack.java:79) ~[mekanism:10.1.2]
	at mekanism.api.chemical.ChemicalUtils.readGasStack(ChemicalUtils.java:49) ~[mekanism:10.1.2]
	at mekanism.common.integration.lookingat.theoneprobe.TOPChemicalElement$GasElement.<init>(TOPChemicalElement.java:33) ~[mekanism:10.1.2]
	at mcjty.theoneprobe.apiimpl.ProbeInfo.createElements(ProbeInfo.java:28) ~[theoneprobe:1.16-3.1.7]
	at mcjty.theoneprobe.apiimpl.ProbeInfo.fromBytes(ProbeInfo.java:15) ~[theoneprobe:1.16-3.1.7]
	at mcjty.theoneprobe.network.PacketReturnInfo.<init>(PacketReturnInfo.java:25) ~[theoneprobe:1.16-3.1.7]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$0(IndexedMessageCodec.java:106) ~[forge:?]
	at java.util.Optional.map(Optional.java:215) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:106) ~[forge:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:148) ~[forge:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:66) ~[forge:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:72) ~[forge:?]
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:77) ~[forge:?]
	at java.util.Optional.map(Optional.java:215) ~[?:?]
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:77) ~[forge:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147240_a(ClientPlayNetHandler.java:1905) ~[?:?]
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:59) ~[?:?]
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:11) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:948) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) ~[量子科技.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) ~[forge-1.16.5-36.2.41.jar:36.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71) [JavaWrapper.jar:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:51) [JavaWrapper.jar:?]
