### ISSUE TITLE
theoneprobe:returninfo: java.lang.NullPointerException

### ISSUE THREAD

**Issue by Darinth** [McJty/TheOneProbe#657]
Currently running a fairly light "Vanilla+" style modpack. Had a player inform me that he was having issues with crashing when breaking kelp he would have game crashes. I test and was pretty able to reproduce the crash. Looking at the server logs, each crash is accompanied by the following exception trace.

```
[20:54:29] [Netty Server IO #20/ERROR] [minecraft/Connection]: Exception caught in connection
io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:custom_payload'
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:55) ~[server-1.21.1-20240808.144430-srg.jar%23128!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:14) ~[server-1.21.1-20240808.144430-srg.jar%23128!/:?] {re:classloading}
        at TRANSFORMER/neoforge@21.1.68/net.neoforged.neoforge.network.filters.GenericPacketSplitter.encode(GenericPacketSplitter.java:104) ~[neoforge-21.1.68-universal.jar%23129!/:?] {re:classloading}
        at TRANSFORMER/neoforge@21.1.68/net.neoforged.neoforge.network.filters.GenericPacketSplitter.encode(GenericPacketSplitter.java:39) ~[neoforge-21.1.68-universal.jar%23129!/:?] {re:classloading}
        at MC-BOOTSTRAP/io.netty.codec@4.1.97.Final/io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[netty-codec-4.1.97.Final.jar%23104!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.codec@4.1.97.Final/io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.97.Final.jar%23104!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.Connection$2.write(Connection.java:528) ~[server-1.21.1-20240808.144430-srg.jar%23128!/:?] {re:classloading}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.Connection.doSendPacket(Connection.java:364) ~[server-1.21.1-20240808.144430-srg.jar%23128!/:?] {re:classloading,re:mixin}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.Connection.lambda$sendPacket$12(Connection.java:359) ~[server-1.21.1-20240808.144430-srg.jar%23128!/:?] {re:classloading,re:mixin}
        at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar%23105!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar%23105!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar%23105!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar%23105!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar%23105!/:4.1.97.Final] {}
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?] {}
Caused by: java.lang.RuntimeException: Failed encoding custom payload theoneprobe:returninfo: java.lang.NullPointerException
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.protocol.common.custom.CustomPacketPayload$1.writeCap(CustomPacketPayload.java:42) ~[server-1.21.1-20240808.144430-srg.jar%23128!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.protocol.common.custom.CustomPacketPayload$1.encode(CustomPacketPayload.java:47) ~[server-1.21.1-20240808.144430-srg.jar%23128!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.protocol.common.custom.CustomPacketPayload$1.encode(CustomPacketPayload.java:29) ~[server-1.21.1-20240808.144430-srg.jar%23128!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$4.encode(StreamCodec.java:81) ~[server-1.21.1-20240808.144430-srg.jar%23128!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$5.encode(StreamCodec.java:97) ~[server-1.21.1-20240808.144430-srg.jar%23128!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$5.encode(StreamCodec.java:87) ~[server-1.21.1-20240808.144430-srg.jar%23128!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:53) ~[server-1.21.1-20240808.144430-srg.jar%23128!/:?] {re:classloading}
        ... 31 more
Caused by: java.lang.NullPointerException
```

At a quick glance, this would seem to be an issue with TOP. I'm running TheOneProbe - 1.21_neo-12.0.3, which is the most recent on curseforge as of this writing. Let me know if I can provide any more details.

**Comment by McJty** [comment]
I'll check it out. Do you happen to know what the player was looking at when this happened?

**Comment by Darinth** [comment]
I know that I was able to reproduce it by going to an ocean biome and breaking kelp. It's not a guaranteed immediate crash, but it didn't take more than probably 10-15 seconds of running around breaking kelp at random to trigger the exception. It was consistent enough that I was able to reproduce it on demand.

https://www.curseforge.com/minecraft/modpacks/sulphurous-skies

There's the modpack I put together on the off chance it could be an interaction with something else. But I feel I'd be a bit surprised, it's a pretty light pack.

**Comment by netvip3r** [comment]
I can 100% reproduce this by breaking "minecraft:seagrass" in MP set as either survival or creative. SP causes no problems.

For us, the server doesn't crash, but the specific client breaking the Seagrass get's kicked. Client can reconnect again as if nothing happened.

Attempted:
```
blacklistEntities = ["minecraft:seagrass"]
```
and still "Nulls"

The log is 99% identical to the one provided above, with the exception that we're running neoforge@21.1.72

-- 

Was not tested with only ToP. Will attempt 'soon' if time permits, but thought adding specific block to reproduce 'might' help.

Log:
```
[21:52:33] [Netty Epoll Server IO #2/ERROR] [minecraft/Connection]: Exception caught in connection
io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:custom_payload'
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:55) ~[server-1.21.1-20240808.144430-srg.jar%23194!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:14) ~[server-1.21.1-20240808.144430-srg.jar%23194!/:?] {re:classloading}
        at TRANSFORMER/neoforge@21.1.72/net.neoforged.neoforge.network.filters.GenericPacketSplitter.encode(GenericPacketSplitter.java:104) ~[neoforge-21.1.72-universal.jar%23195!/:?] {re:classloading}
        at TRANSFORMER/neoforge@21.1.72/net.neoforged.neoforge.network.filters.GenericPacketSplitter.encode(GenericPacketSplitter.java:39) ~[neoforge-21.1.72-universal.jar%23195!/:?] {re:classloading}
        at MC-BOOTSTRAP/io.netty.codec@4.1.97.Final/io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[netty-codec-4.1.97.Final.jar%23104!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.codec@4.1.97.Final/io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.97.Final.jar%23104!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.Connection$2.write(Connection.java:528) ~[server-1.21.1-20240808.144430-srg.jar%23194!/:?] {re:classloading}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.Connection.doSendPacket(Connection.java:364) ~[server-1.21.1-20240808.144430-srg.jar%23194!/:?] {re:classloading,re:mixin}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.Connection.lambda$sendPacket$12(Connection.java:359) ~[server-1.21.1-20240808.144430-srg.jar%23194!/:?] {re:classloading,re:mixin}
        at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar%23105!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar%23105!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar%23105!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport.classes.epoll@4.1.97.Final/io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[netty-transport-classes-epoll-4.1.97.Final.jar%23109!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar%23105!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar%23105!/:4.1.97.Final] {}
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?] {}
Caused by: java.lang.RuntimeException: Failed encoding custom payload theoneprobe:returninfo: java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.ResourceLocation.toString()" because "p_130086_" is null
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.protocol.common.custom.CustomPacketPayload$1.writeCap(CustomPacketPayload.java:42) ~[server-1.21.1-20240808.144430-srg.jar%23194!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.protocol.common.custom.CustomPacketPayload$1.encode(CustomPacketPayload.java:47) ~[server-1.21.1-20240808.144430-srg.jar%23194!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.protocol.common.custom.CustomPacketPayload$1.encode(CustomPacketPayload.java:29) ~[server-1.21.1-20240808.144430-srg.jar%23194!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$4.encode(StreamCodec.java:81) ~[server-1.21.1-20240808.144430-srg.jar%23194!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$5.encode(StreamCodec.java:97) ~[server-1.21.1-20240808.144430-srg.jar%23194!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$5.encode(StreamCodec.java:87) ~[server-1.21.1-20240808.144430-srg.jar%23194!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:53) ~[server-1.21.1-20240808.144430-srg.jar%23194!/:?] {re:classloading}
        ... 31 more
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.ResourceLocation.toString()" because "p_130086_" is null
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.FriendlyByteBuf.writeResourceLocation(FriendlyByteBuf.java:571) ~[server-1.21.1-20240808.144430-srg.jar%23194!/:?] {re:classloading}
        at TRANSFORMER/theoneprobe@1.21_neo-12.0.3/mcjty.theoneprobe.apiimpl.elements.ElementIcon.toBytes(ElementIcon.java:66) ~[theoneprobe-1.21_neo-12.0.3.jar%23263!/:1.21_neo-12.0.3] {re:classloading}
        at TRANSFORMER/theoneprobe@1.21_neo-12.0.3/mcjty.theoneprobe.apiimpl.ProbeInfo.writeElements(ProbeInfo.java:64) ~[theoneprobe-1.21_neo-12.0.3.jar%23263!/:1.21_neo-12.0.3] {re:classloading}
        at TRANSFORMER/theoneprobe@1.21_neo-12.0.3/mcjty.theoneprobe.apiimpl.elements.AbstractElementPanel.toBytes(AbstractElementPanel.java:74) ~[theoneprobe-1.21_neo-12.0.3.jar%23263!/:1.21_neo-12.0.3] {re:classloading}
        at TRANSFORMER/theoneprobe@1.21_neo-12.0.3/mcjty.theoneprobe.apiimpl.ProbeInfo.writeElements(ProbeInfo.java:64) ~[theoneprobe-1.21_neo-12.0.3.jar%23263!/:1.21_neo-12.0.3] {re:classloading}
        at TRANSFORMER/theoneprobe@1.21_neo-12.0.3/mcjty.theoneprobe.apiimpl.elements.AbstractElementPanel.toBytes(AbstractElementPanel.java:74) ~[theoneprobe-1.21_neo-12.0.3.jar%23263!/:1.21_neo-12.0.3] {re:classloading}
        at TRANSFORMER/theoneprobe@1.21_neo-12.0.3/mcjty.theoneprobe.apiimpl.ProbeInfo$1.encode(ProbeInfo.java:36) ~[theoneprobe-1.21_neo-12.0.3.jar%23263!/:1.21_neo-12.0.3] {re:classloading}
        at TRANSFORMER/theoneprobe@1.21_neo-12.0.3/mcjty.theoneprobe.apiimpl.ProbeInfo$1.encode(ProbeInfo.java:20) ~[theoneprobe-1.21_neo-12.0.3.jar%23263!/:1.21_neo-12.0.3] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$9.encode(StreamCodec.java:181) ~[server-1.21.1-20240808.144430-srg.jar%23194!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.protocol.common.custom.CustomPacketPayload$1.writeCap(CustomPacketPayload.java:40) ~[server-1.21.1-20240808.144430-srg.jar%23194!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.protocol.common.custom.CustomPacketPayload$1.encode(CustomPacketPayload.java:47) ~[server-1.21.1-20240808.144430-srg.jar%23194!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.protocol.common.custom.CustomPacketPayload$1.encode(CustomPacketPayload.java:29) ~[server-1.21.1-20240808.144430-srg.jar%23194!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$4.encode(StreamCodec.java:81) ~[server-1.21.1-20240808.144430-srg.jar%23194!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$5.encode(StreamCodec.java:97) ~[server-1.21.1-20240808.144430-srg.jar%23194!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$5.encode(StreamCodec.java:87) ~[server-1.21.1-20240808.144430-srg.jar%23194!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:53) ~[server-1.21.1-20240808.144430-srg.jar%23194!/:?] {re:classloading}
        ... 31 more
[21:52:33] [Server thread/INFO] [minecraft/ServerGamePacketListenerImpl]: PlayerName lost connection: Internal Exception: io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:custom_payload'
[21:52:33] [Server thread/INFO] [minecraft/MinecraftServer]: PlayerName left the game
```

**Comment by McJty** [comment]
Based on the latest crashlog I did a blind fix. Let me know if The One Probe 12.0.5 fixes the problem

**Comment by Darinth** [comment]
I see the new version on modrinth, for my future reference are you intending to drop curse forge support or just haven't gotten around to doing uploads there? I don't see either of the two most recent versions there. In general, I'm trying to continue to gauge community feelings and figure out what is going to be the easiest to put together packs in the future.

**Comment by Darinth** [comment]
And test server with updated mod version appears to work perfectly fine. I was unable to reproduce. 👍 Thank you.

**Comment by McJty** [comment]
I always release my mods on CurseForge and Modrinth at the same time. The One Probe can be found there

**Comment by Darinth** [comment]
TOP itself is on curseforge, but I'm not finding the two most recent versions. Everything 12.0.3 and prior seems to be showing up, but neither 12.0.4 nor 12.0.5 are there.

<img width="643" alt="image" src="https://github.com/user-attachments/assets/a017e497-5ce6-444e-8ce2-6044e6c6258b">
 
All game versions, all mod loaders, sorted by upload date. I asked because I assumed that was intentional.

**Comment by McJty** [comment]
Oh you are right. Somehow my release script broke. I'll check it out

**Comment by Darinth** [comment]
Cool beans. 👍

**Comment by McJty** [comment]
Ok, it's there now

**Comment by Darinth** [comment]
Thank you for all you do! ❤️
