### ISSUE TITLE
Server log stacktrace spam in 1.10-1.3.2

### ISSUE THREAD

**Issue by dashkal16** [McJty/TheOneProbe#88]
Forge 2122
mcjtylib-1.10-2.2.0.jar
theoneprobe-1.10-1.3.2.jar

I get a ton of this spam in the server logs whenever I look at any block.
Occurs in both modes 2 and 3.

`[19:49:49] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.entity.player.InventoryPlayer.func_70440_f(I)Lnet/minecraft/item/ItemStack;
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_91]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_91]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.player.InventoryPlayer.func_70440_f(I)Lnet/minecraft/item/ItemStack;
        at mcjty.theoneprobe.items.ModItems.hasProbeInHelmet(ModItems.java:150) ~[ModItems.class:?]
        at mcjty.theoneprobe.items.ModItems.hasAProbeSomewhere(ModItems.java:140) ~[ModItems.class:?]
        at mcjty.theoneprobe.network.PacketGetInfo.getProbeInfo(PacketGetInfo.java:125) ~[PacketGetInfo.class:?]
        at mcjty.theoneprobe.network.PacketGetInfo.access$600(PacketGetInfo.java:33) ~[PacketGetInfo.class:?]
        at mcjty.theoneprobe.network.PacketGetInfo$Handler.handle(PacketGetInfo.java:109) ~[PacketGetInfo$Handler.class:?]
        at mcjty.theoneprobe.network.PacketGetInfo$Handler.lambda$onMessage$0(PacketGetInfo.java:102) ~[PacketGetInfo$Handler.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_91]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
        ... 5 more
`

**Comment by Towsty** [comment]
Exact same, creating massive log files.

**Comment by McJty** [comment]
I will check it out

**Comment by McJty** [comment]
Fixed next release (soon)
