### ISSUE TITLE
[Bug][1.10.2] SuperCircuitMaker

### ISSUE THREAD

**Issue by cookta2012** [McJty/TheOneProbe#91]
When you have the one probe active and you look at a complex SCM circuit you will either crash or the internal server will "Shutdown" crash. I will add screenshots in a few moments.

**Comment by McJty** [comment]
Report this on the SCM tracker as it is likely a bug with that mod. Also make sure you have crash logs

**Comment by cookta2012** [comment]
It has to do with the packet size being too big, and I will post logs too

**Comment by cookta2012** [comment]
![capture](https://cloud.githubusercontent.com/assets/1284410/20311457/7d0132ec-ab15-11e6-86d3-67a7ffe9ceef.PNG)
`[09:23:59] [Netty Local Client IO #0/ERROR] [FML]: NetworkDispatcher exception
java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes
    at net.minecraft.network.play.client.CPacketCustomPayload.<init>(CPacketCustomPayload.java:28) ~[it.class:?]
    at net.minecraftforge.fml.common.network.internal.FMLProxyPacket.toC17Packet(FMLProxyPacket.java:143) ~[FMLProxyPacket.class:?]
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.write(NetworkDispatcher.java:527) ~[NetworkDispatcher.class:?]
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658) ~[AbstractChannelHandlerContext.class:4.0.23.Final]
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716) ~[AbstractChannelHandlerContext.class:4.0.23.Final]
    at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706) ~[AbstractChannelHandlerContext.class:4.0.23.Final]
    at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741) ~[AbstractChannelHandlerContext.class:4.0.23.Final]
    at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895) ~[DefaultChannelPipeline.class:4.0.23.Final]
    at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240) ~[AbstractChannel.class:4.0.23.Final]
    at net.minecraft.network.NetworkManager$4.run(NetworkManager.java:247) [eo$4.class:?]
    at io.netty.channel.local.LocalEventLoop.run(LocalEventLoop.java:33) [LocalEventLoop.class:4.0.23.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [SingleThreadEventExecutor$2.class:4.0.23.Final]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]`

**Comment by McJty** [comment]
yes, please report on the SCM Tracker

**Comment by cookta2012** [comment]
Spoke with Ama, he says that this is because you are passing the complete tile information in one packet when you need to split it up.

**Comment by cookta2012** [comment]
When all information is shown

**Comment by josephcsible** [comment]
Merging with #215
